### ISSUE TITLE
cloudflare.com limits

### ISSUE THREAD

**Issue by AndreyKravchina** [wavedocs/freedns#16]
В бесплатном плане только 500’000 запросов. Это меньше 1к/час. Желательно внести информацию в доп инфо.

**Comment by DarkPark** [comment]
@AndreyKravchina укажите пожалуйста источник информации, а то все что нашел - это ровно наоборот
https://support.cloudflare.com/hc/en-us/articles/203502550-Does-Cloudflare-charge-for-or-limit-DNS-queries-

**Comment by AndreyKravchina** [comment]
https://www.cloudflare.com/plans/#compare-features

First 500k DNS requests are free.

$.50 per every 500k DNS requests after.

**Comment by DarkPark** [comment]
@AndreyKravchina это относится к услуге Load Balancing

**Comment by wavedocs** [comment]
Согласен с @DarkPark, данное ограничение относится к LB
